const EXPERIENCES = [
  {
    id: 1,
    title: "Senior Software Engineer",
    company: "Jukto Digital",
    job: false,
    location: "Khulna, Bangladesh",
    href: "https://jukto.digital/",
    duration: "Full-Time | Oct 2021 - Present",
    description: `Led the end-to-end development of a Learning Management System (LMS) focused on automating and scaling core academic functions, with a practical foundation for AI-integrated education systems.`,
    tasks: [
      "Built modular assessment and reporting tools enabling dynamic form generation, customizable evaluation methods, and automated progress tracking.",
      "Enhanced learning analytics and system reliability via update tracking, soft delete functionality, and structured data recovery mechanisms.",
      "Implemented personalized student dashboards, attendance tracking, certificate generation, and timeline-based study planning features.",
    ],
    badge: [
      "React.js",
      "React Native",
      "Next.js",
      "Django REST",
      "Koa.js",
      "MongoDB",
      "MySQL",
      "Tailwind CSS",
      "Shadcn UI",
      "Material UI",
      "Team Leadership",
      "LMS Development",
      "Learning Analytics",
      "AI Integration",
    ],
  },
  {
    id: 3,
    title: "Industrial Expert Trainer",
    company: "EDGE-KUCSE Digital Skills Training",
    job: true,
    location: "Khulna, Bangladesh; Seasonal",
    href: "https://www.facebook.com/edge.kucse/",
    duration: "Part-Time |Apr 2025 – Jul 2025",
    description: `Served as an Industrial Expert Trainer for the EDGE Project, conducting hands-on training in Python and Data Science, guiding participants with practical coding exercises and project-based learning.`,
    tasks: [
      "Conducted workshops on Python Programming and Basic Data Science for multiple participant batches.",
      "Designed sessions combining theory, presentations, and project-based exercises.",
      "Guided participants with little to no programming background through practical coding, data handling, and predictive modeling techniques.",
    ],
    badge: [
      "Python",
      "Data Science",
      "Teaching",
      "Workshop Delivery",
      "Project-Based Learning",
      "Mentorship",
    ],
  },
  {
    id: 2,
    title: "Junior Software Engineer",
    company: "Softspace AB (Startup)",
    job: true,
    location: "Malmø, Sweden; Remote",
    href: "https://www.linkedin.com/company/softspace-ab/",
    duration: "Full-Time | Jun 2020 - Sept 2021",
    description: `Contributed to full-stack development of a social networking platform with Facebook-like features, improving security, performance, and user experience.`,
    tasks: [
      "Developed frontend interfaces and backend logic for social networking platform features.",
      "Implemented two-step verification and a custom role-based access control (RBAC) system to improve security.",
      "Troubleshot production issues via source code analysis, network trace review, and configuration debugging, resulting in 15% performance improvement.",
    ],
    badge: [
      "React.js",
      "Node.js",
      "JavaScript",
      "Frontend Development",
      "Backend Development",
      "Agile",
    ],
  },
];

export default EXPERIENCES;
